"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SimpleTestMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STRING_FIELD_FIELD_NUMBER: builtins.int
    INT_FIELD_FIELD_NUMBER: builtins.int
    BOOL_FIELD_FIELD_NUMBER: builtins.int
    REPEATED_STRING_FIELD_FIELD_NUMBER: builtins.int
    string_field: builtins.str
    int_field: builtins.int
    bool_field: builtins.bool
    @property
    def repeated_string_field(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        string_field: builtins.str = ...,
        int_field: builtins.int = ...,
        bool_field: builtins.bool = ...,
        repeated_string_field: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bool_field", b"bool_field", "int_field", b"int_field", "repeated_string_field", b"repeated_string_field", "string_field", b"string_field"]) -> None: ...

global___SimpleTestMessage = SimpleTestMessage

@typing.final
class NestedTestMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SIMPLE_MESSAGE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    description: builtins.str
    @property
    def simple_message(self) -> global___SimpleTestMessage: ...
    def __init__(
        self,
        *,
        simple_message: global___SimpleTestMessage | None = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["simple_message", b"simple_message"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "simple_message", b"simple_message"]) -> None: ...

global___NestedTestMessage = NestedTestMessage

@typing.final
class EqualityMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    AGE_FIELD_NUMBER: builtins.int
    name: builtins.str
    age: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        age: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["age", b"age", "name", b"name"]) -> None: ...

global___EqualityMessage = EqualityMessage
